column_width = 120
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferSingle"
call_parentheses = "NoSingleString"
collapse_simple_statement = "Never"
space_after_function_names = "Never"

[sort_requires]
enabled = true
