return {
    'folke/which-key.nvim',
    event = 'VimEnter',
    opts = {
        plugins = { spelling = true },
        defaults = {
            mode = { 'n', 'v' },
            [']'] = { name = '+next' },
            ['['] = { name = '+prev' },
            ['<leader>b'] = { desc = 'buffer next/prev' },
            ['<leader>ch'] = { desc = 'code/chat gippity' },
            ['<leader>e'] = { desc = 'neotree' },
            ['<leader>g'] = { desc = 'git' },
            ['<leader>h'] = { desc = 'harpoon' },
            ['<leader>l'] = { desc = 'list session' },
            ['<leader>t'] = { desc = 'todo comments' },
            ['<leader>v'] = { desc = 'vim maximize' },
            ['<leader>z'] = { desc = 'code folding' },
        },
    },
    keys = {
        { '<leader>c', group = '[C]ode' },
        { '<leader>c_', hidden = true },
        { '<leader>d', group = '[D]ocument' },
        { '<leader>d_', hidden = true },
        { '<leader>r', group = '[R]ename' },
        { '<leader>r_', hidden = true },
        { '<leader>s', group = '[S]earch' },
        { '<leader>s_', hidden = true },
        { '<leader>w', group = '[W]orkspace' },
        { '<leader>w_', hidden = true },
    },
}
